classDiagram
direction LR

class User {
  id : String
  name : String
  getName : void
}

class Trainer {
  specialization : String
  createMonthlyPlan : void
  adjustLoad : void
}

class Client {
  age : int
  markWorkoutDone : void
  reportInjury : void
}

User <|-- Trainer
User <|-- Client


class FitnessApp {
  registerClient : void
  connectDevice : void
  importHealthData : void
}


class MonthlyPlan {
  month : String
  goal : String
  addWorkout : void
  calculateAdherence : void
}


class Workout {
  workoutId : String
  date : String
  load : int
  markDone : void
  setLoad : void
}


class InjuryReport {
  type : String
  description : String
  date : String
}


class HealthData {
  averagePulse : int
  sleepHours : float
}


class DataProvider {
  fetchHealthData : void
}


class WearableDevice {
  deviceId : String
  fetchHealthData : void
}


DataProvider <|-- WearableDevice

FitnessApp o-- Client
FitnessApp o-- WearableDevice
MonthlyPlan *-- Workout

Trainer ..> MonthlyPlan
Trainer ..> InjuryReport
Client ..> MonthlyPlan
Client ..> InjuryReport
FitnessApp ..> DataProvider
